version: '3'
services:
  # PHP Service
  php:
    image: php:7.4-apache
    container_name: php
    ports:
      - "80:80"
    volumes:
      - ./PHP:/var/www/html # Replace './php-app' with your PHP application code location
    networks:
      - php-mariadb-network

  # MariaDB Service
  mariadb:
    image: mariadb:latest
    container_name: mariadb
    environment:
      MYSQL_ROOT_PASSWORD: super_secret123?
      MYSQL_DATABASE: Liams
      MYSQL_USER: w0469100
      MYSQL_PASSWORD: secret_pwd123?
    ports:
      - "8089:3306"
    volumes:
      - ./mysql-data:/var/lib/mysql # Replace './mysql-data' with your MariaDB data location
    networks:
      - php-mariadb-network

networks:
  php-mariadb-network:
